"""add_report_and_pdf_columns

Revision ID: 2760e9b15bfa
Revises: 3e219e7c94db
Create Date: 2026-06-19 01:15:09.272536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2760e9b15bfa'
down_revision: Union[str, None] = '3e219e7c94db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('report_url', sa.String(length=1000), nullable=True))
    op.add_column('dashboards', sa.Column('long_description', sa.Text(), nullable=True))
    op.add_column('dashboards', sa.Column('report_type', sa.String(length=50), server_default='Power BI', nullable=True))
    op.add_column('tools', sa.Column('documentation_pdf_path', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'documentation_pdf_path')
    op.drop_column('dashboards', 'report_type')
    op.drop_column('dashboards', 'long_description')
    op.drop_column('dashboards', 'report_url')
    # ### end Alembic commands ###
